use std::rc::Rc;
use timely::dataflow::operators::capture::event::link::EventLink;
use timely::dataflow::operators::capture::Replay;
use timely::dataflow::{Scope, Stream};

use crate::event::{Auction, Bid, Date, Person};

mod window_1_faster;
mod window_1_faster_count;
mod window_1_faster_count_custom_slice;
mod window_1_faster_rank;
mod window_1_faster_rank_custom_slice;
mod window_2_faster;
mod window_1_rocksdb;
mod window_1_rocksdb_count;
mod window_1_rocksdb_rank;
mod window_2a_rocksdb;
mod window_2a_rocksdb_count;
mod window_2a_rocksdb_rank;
mod window_2b_rocksdb;
mod window_2b_rocksdb_count;
mod window_2b_rocksdb_rank;
mod window_2_faster_count;
mod window_2_faster_rank;
mod window_3_faster;
mod window_3a_rocksdb;
mod window_3a_rocksdb_count;
mod window_3a_rocksdb_rank;
mod window_3b_rocksdb;
mod window_3b_rocksdb_count;
mod window_3b_rocksdb_rank;
mod window_3_faster_count;
mod window_3_faster_rank;

pub use self::window_1_rocksdb::window_1_rocksdb;
pub use self::window_1_rocksdb_count::window_1_rocksdb_count;
pub use self::window_1_rocksdb_rank::window_1_rocksdb_rank;
pub use self::window_2a_rocksdb::window_2a_rocksdb;
pub use self::window_2a_rocksdb_count::window_2a_rocksdb_count;
pub use self::window_2a_rocksdb_rank::window_2a_rocksdb_rank;
pub use self::window_2b_rocksdb::window_2b_rocksdb;
pub use self::window_2b_rocksdb_count::window_2b_rocksdb_count;
pub use self::window_2b_rocksdb_rank::window_2b_rocksdb_rank;
pub use self::window_3a_rocksdb::window_3a_rocksdb;
pub use self::window_3a_rocksdb_count::window_3a_rocksdb_count;
pub use self::window_3a_rocksdb_rank::window_3a_rocksdb_rank;
pub use self::window_3b_rocksdb::window_3b_rocksdb;
pub use self::window_3b_rocksdb_count::window_3b_rocksdb_count;
pub use self::window_3b_rocksdb_rank::window_3b_rocksdb_rank;
pub use self::window_1_faster::window_1_faster;
pub use self::window_1_faster_count::window_1_faster_count;
pub use self::window_1_faster_count_custom_slice::window_1_faster_count_custom_slice;
pub use self::window_1_faster_rank::window_1_faster_rank;
pub use self::window_1_faster_rank_custom_slice::window_1_faster_rank_custom_slice;
pub use self::window_2_faster::window_2_faster;
pub use self::window_2_faster_count::window_2_faster_count;
pub use self::window_2_faster_rank::window_2_faster_rank;
pub use self::window_3_faster::window_3_faster;
pub use self::window_3_faster_count::window_3_faster_count;
pub use self::window_3_faster_rank::window_3_faster_rank;
